export type CategoryContent = {
  title: string; intro: string; checklist: string[]; guideSlug: string; guideLabel: string;
  research?: { heading: string; paragraphs: string[] }[];
  qcChecks?: string[]; faq?: { question: string; answer: string }[];
};

const focusedCategories: Record<string, CategoryContent> = {
  sneakers: {
    title: 'Oopbuy Sneaker Spreadsheet', intro: 'Browse sneaker listings by style and price context, then verify the exact colourway, size chart and live seller photos before adding anything to your agent.',
    checklist: ['Match the colourway and SKU details to the current listing.', 'Use the seller’s insole or length measurements, not just your usual size.', 'Compare current photos, price and available variants before ordering.'], guideSlug: 'oopbuy-qc-photos', guideLabel: 'Read the QC photo guide',
    research: [
      { heading: 'How to use an Oopbuy sneaker spreadsheet', paragraphs: ['Use this page to group comparable sneaker listings, not to treat a card as a live purchase offer. Start with a model or colourway, open a small number of current listings, then record the exact size option and the measurements you need to compare.', 'Titles, cover images and price ranges can describe different versions of a shoe. The live listing and selected option are the source for current availability, price and size information.'] },
      { heading: 'Size and specification checks', paragraphs: ['For sneakers, insole or internal length is usually more useful than a familiar regional size label. Compare the seller’s measurement method with a pair you already own and know fits. If the chart does not say what it measures, treat that as an unresolved detail.', 'Also confirm the colourway, material description and included components on the live page. A similar title can hide a different option, batch or accessory.'] }
    ], qcChecks: ['Confirm the visible size label and selected colourway against the order record.', 'Compare left and right shoes for obvious mismatches, then check soles, heel tabs and included accessories.', 'Use several warehouse angles; a QC count is not a quality grade or fit guarantee.'],
    faq: [{ question: 'How do I choose a sneaker size from an Oopbuy listing?', answer: 'Use the seller’s insole or internal-length measurement and compare it with a shoe you already own. Do not rely on the size label alone.' }, { question: 'Do QC photos prove a sneaker is good?', answer: 'No. They can help identify visible order mismatches, but they are not an authenticity, durability or comfort guarantee.' }, { question: 'Why does a sneaker card show a different price on the live page?', answer: 'The card may refer to a different option or an earlier snapshot. Confirm the price of the exact live variant before ordering.' }]
  },
  'hoodies-sweatshirts': {
    title: 'Oopbuy Hoodies & Sweatshirts Spreadsheet', intro: 'Use this category to discover hoodies and sweatshirts, compare price ranges and move from a quick shortlist to the live listing with the details that matter.',
    checklist: ['Check garment measurements for chest, length and shoulder width.', 'Confirm fabric, colour and print details in the current seller photos.', 'Review the live size options before you submit the link.'], guideSlug: 'how-to-use-oopbuy-spreadsheet', guideLabel: 'How to use a spreadsheet well',
    research: [
      { heading: 'Research hoodies by fit, not only by label', paragraphs: ['A hoodie spreadsheet is most useful when it narrows a large category into a few cuts you can compare. Decide whether you want a cropped, regular, relaxed or oversized fit before looking at the familiar size label.', 'Open the live page for each candidate and compare the selected size’s chest, length, shoulder and sleeve measurements with a hoodie you already wear. Seller charts can use different measuring methods.'] },
      { heading: 'Read the listing details that affect a hoodie', paragraphs: ['Fabric notes, lining, zip hardware, pocket construction, print placement and colour can materially change the item you receive. Use current listing photos to identify the details that matter to you, rather than assuming two similar cover images describe the same garment.', 'If the selected option is unclear, keep it off the shortlist until you can identify it. A clear comparison is more useful than a longer list of uncertain candidates.'] }
    ], qcChecks: ['Check the visible size tag and selected colour against your order record.', 'Review print placement, seams, zip, pocket and drawstring details from more than one angle.', 'Use QC photos to identify a visible mismatch, not to predict fabric feel or fit.'],
    faq: [{ question: 'What should I measure for an Oopbuy hoodie?', answer: 'Compare chest, length, shoulder and sleeve measurements with a hoodie you already own. Check whether the seller chart uses flat garment measurements.' }, { question: 'Can I assume an oversized hoodie fits the same as my usual size?', answer: 'No. Intended fit and seller measurements vary. Use the current chart for the exact option.' }, { question: 'What can warehouse QC photos confirm for a hoodie?', answer: 'They can help confirm the visible size label, colour and construction details, but cannot guarantee comfort, fabric weight or final fit.' }]
  },
  'bags-backpacks': {
    title: 'Oopbuy Bags & Backpacks Spreadsheet', intro: 'Explore bags and backpacks by type, then check dimensions, closure details and interior photos on the live listing before you order.',
    checklist: ['Compare listed dimensions with what you actually need to carry.', 'Check strap, zip and interior details in the current photos.', 'Confirm the live colour and material options before ordering.'], guideSlug: 'how-to-use-oopbuy-spreadsheet', guideLabel: 'Read the spreadsheet guide',
    research: [
      { heading: 'Start with the use case', paragraphs: ['A bag or backpack title rarely tells you whether it will hold what you need. Begin with the actual use case—daily carry, laptop, travel, small essentials or a particular item—and compare the listed dimensions with the items you plan to carry.', 'Check whether measurements describe the exterior, interior or an expanded shape. Product photos can help you understand layout, but the live dimension information should guide the decision.'] },
      { heading: 'Compare construction details on the live listing', paragraphs: ['Inspect the closure, straps, handles, interior pockets, hardware and material description before you shortlist an option. These are often the practical differences between similar-looking bags.', 'Treat a card image as a lead only. Confirm the exact colour and selected option on the live page, especially when a listing groups several sizes or materials together.'] }
    ], qcChecks: ['Confirm the ordered colour, size and any included strap or accessory.', 'Check visible zips, hardware, handles, strap attachment and interior layout where shown.', 'Compare the item with the live listing; warehouse photos do not prove capacity, durability or material composition.'],
    faq: [{ question: 'How do I compare bag sizes on an Oopbuy listing?', answer: 'Compare the stated dimensions with the items you plan to carry and confirm whether the measurements refer to exterior or interior space.' }, { question: 'What should I look for in bag QC photos?', answer: 'Check the selected colour, visible hardware, straps, closures and included components against your order record.' }, { question: 'Can product photos tell me whether a bag is durable?', answer: 'No. Photos can show visible details, but they cannot guarantee construction strength or long-term durability.' }]
  },
  belts: {
    title: 'Oopbuy Belt Spreadsheet', intro: 'Browse belt listings by style and price context, then verify the stated length, width, buckle type and live option details before ordering.',
    checklist: ['Compare the stated belt length and width with a belt you already use.', 'Confirm the selected colour, buckle and material description on the live listing.', 'Check whether the listed length includes the buckle and which holes or adjustment range it covers.'], guideSlug: 'oopbuy-size-guide', guideLabel: 'Read the size and measurement guide',
    research: [
      { heading: 'Measure a belt you already wear', paragraphs: ['For belt finds, the most useful reference is a belt that fits the way you want. Measure from the buckle end to the hole you actually use, then compare that method with the seller’s stated length. A total length can be different from a wearable length.', 'Also compare width with the belt loops you plan to use. A visually similar belt can be impractical if its width or buckle profile does not suit your clothing.'] },
      { heading: 'Confirm the exact buckle and option', paragraphs: ['Many belt listings combine colours, buckle styles, lengths and material descriptions under one title. Open the live listing and make sure the selected option matches the photo and written details you intend to order.', 'If the listing does not explain its measurement method or adjustment range, do not convert a vague label into a confident size choice. Keep that uncertainty in your research note.'] }
    ], qcChecks: ['Confirm the ordered length, colour and buckle style against the order record.', 'Check visible belt holes, buckle finish, hardware placement and included accessories.', 'Use the warehouse set to compare the received item with the selected option; it cannot confirm comfort or material durability.'],
    faq: [{ question: 'How should I measure a belt before ordering?', answer: 'Measure from the buckle end to the hole you use on a belt that fits, then compare that method with the seller’s stated measurement.' }, { question: 'Does total belt length equal my waist size?', answer: 'Not necessarily. Listings can measure total length, usable length or a different point. Read the seller chart before choosing.' }, { question: 'What can QC photos confirm for a belt?', answer: 'They can help confirm visible length labels, buckle style, colour and hardware placement against your order record.' }]
  },
  'jewelry-watches': {
    title: 'Oopbuy Jewelry & Watches Spreadsheet', intro: 'Browse jewelry and watch listings by style, then verify dimensions, closure type, material description and the exact selected option on the live page.',
    checklist: ['Compare stated length, diameter or case dimensions with an item you already use.', 'Confirm the chosen finish, colour, size and included components.', 'Treat a material description as a listing claim to verify, not a guarantee.'], guideSlug: 'oopbuy-qc-photos', guideLabel: 'Read the QC photo guide',
    research: [{ heading: 'Compare specifications before appearance', paragraphs: ['Small accessories can look similar in a cover image while differing in length, clasp, case size, strap width or included pieces. Record the exact detail that matters to you, then confirm it on the live selected option.', 'For watches, compare stated case and strap dimensions with a reference you already wear. For jewelry, compare length and fastening style rather than relying on a familiar product title.'] }, { heading: 'Use current photos for visible details', paragraphs: ['Review current listing photos for finish, colour, closures, markings and components. If the image set cannot show a detail that decides your choice, keep the item as uncertain instead of assuming it matches another listing.', 'This category page is for discovery. The live page remains the source for available options and current information.'] }],
    qcChecks: ['Confirm the selected finish, size and any included component against the order record.', 'Check visible clasps, links, straps, case shape and hardware placement.', 'QC photos can identify visible mismatches but cannot certify materials, water resistance or durability.'],
    faq: [{ question: 'What should I compare for jewelry sizing?', answer: 'Compare stated length, diameter or width with an accessory you already use, and confirm the seller measurement method.' }, { question: 'Can QC photos verify watch performance?', answer: 'No. They can show visible appearance and selected options, but cannot verify performance or durability.' }, { question: 'Why does the finish look different in photos?', answer: 'Lighting and image processing can affect colour. Compare several current images and treat uncertainty honestly.' }]
  },
  eyewear: {
    title: 'Oopbuy Eyewear Spreadsheet', intro: 'Discover eyewear listings, then compare frame width, lens width, bridge and temple measurements before selecting a live option.',
    checklist: ['Compare frame, lens, bridge and temple dimensions with eyewear you own.', 'Confirm the selected colour and lens option on the live page.', 'Check whether a case or other component is included rather than assuming it is.'], guideSlug: 'oopbuy-size-guide', guideLabel: 'Read the measurement guide',
    research: [{ heading: 'Fit starts with frame measurements', paragraphs: ['A frame title or cover photo does not show how it will sit on your face. Compare lens width, bridge width, temple length and total frame width with a pair you already use.', 'If a listing only provides a generic size label, it offers less useful evidence than a listing with clear measurements.'] }, { heading: 'Confirm the selected lens option', paragraphs: ['Some eyewear listings group different colours, lens types or frame shapes together. Open the live page and make sure the selected variant matches the photo and written option details.', 'Use the listing only for product research; do not infer protection, prescription suitability or performance from a product image.'] }],
    qcChecks: ['Check the selected frame colour and visible shape against the order record.', 'Compare left and right temples, hinges, lenses and included accessories where shown.', 'QC photos cannot confirm optical protection, prescription suitability or comfort.'],
    faq: [{ question: 'Which eyewear measurements matter most?', answer: 'Frame width, lens width, bridge and temple length are useful comparisons with a pair you already own.' }, { question: 'Can a photo confirm lens protection?', answer: 'No. Images can show visible features but cannot verify optical or protective performance.' }, { question: 'Should I rely on a generic size label?', answer: 'No. Use actual listing measurements where available.' }]
  },
  headwear: {
    title: 'Oopbuy Headwear Spreadsheet', intro: 'Browse caps, hats and beanies by style, then verify circumference, adjustment method, material and current option details before ordering.',
    checklist: ['Check the stated circumference or adjustment range.', 'Confirm the selected colour and logo or print placement on the live listing.', 'Review material and fastening details before choosing an option.'], guideSlug: 'oopbuy-size-guide', guideLabel: 'Read the size guide',
    research: [{ heading: 'Check adjustment and circumference', paragraphs: ['Headwear fit depends on the actual circumference, adjustment range and construction. Compare any listed range with a hat you already wear rather than assuming one-size means the same thing across listings.', 'For caps, identify the closure type; for beanies, read the fabric and stretch notes.'] }, { heading: 'Compare visible construction details', paragraphs: ['Look for current photos of embroidery, patches, panel shape, brim, seams and adjustment hardware. Similar titles can refer to different versions or colours.', 'Keep a specific note about the chosen option so warehouse photos can later be compared with your order record.'] }],
    qcChecks: ['Confirm the selected colour and visible design details.', 'Check brim, panels, seams, patch or embroidery placement and closure where shown.', 'QC photos can show visible construction, not comfort, stretch or long-term durability.'],
    faq: [{ question: 'How do I choose a hat size?', answer: 'Compare the stated circumference or adjustment range with headwear you already wear.' }, { question: 'What should I check in QC photos?', answer: 'Check colour, visible design placement, panels, brim and closure against the selected option.' }, { question: 'Does one-size guarantee fit?', answer: 'No. Review the adjustment range and material notes.' }]
  },
  audio: {
    title: 'Oopbuy Audio Spreadsheet', intro: 'Browse audio listings by type, then verify model, connection, included accessories and current specifications on the live page before ordering.',
    checklist: ['Confirm the exact model and connection type for the selected option.', 'Check included cables, case, charger or accessories in the listing.', 'Use the live specification and warranty information for technical decisions.'], guideSlug: 'oopbuy-product-comparison', guideLabel: 'Read the product comparison guide',
    research: [{ heading: 'Identify the exact model and option', paragraphs: ['Audio product titles can group colours, storage options, connection types or accessory bundles together. Use the live listing to confirm the exact model and configuration you intend to select.', 'Compare only specifications that are clearly stated on the current page. A similar-looking product card is not evidence that two products have the same features.'] }, { heading: 'Keep technical claims separate from images', paragraphs: ['Photos can help identify visible ports, controls and included accessories, but cannot verify sound quality, battery life, compatibility or safety. Treat technical claims as information to verify on the current destination.', 'Record the model and included accessories before ordering so you can compare the received option against the selected listing later.'] }],
    qcChecks: ['Confirm the selected model, colour and visible included accessories.', 'Check visible ports, controls, cable type and packaging where shown.', 'QC images cannot prove audio performance, battery health, compatibility or warranty coverage.'],
    faq: [{ question: 'What should I verify on an audio listing?', answer: 'Confirm the exact model, connection type, included accessories and current specifications for the selected option.' }, { question: 'Can QC photos prove an audio product works?', answer: 'No. They can show visible components but cannot verify performance, battery health or compatibility.' }, { question: 'Why should I check included accessories?', answer: 'Listings may group bundles and base versions together. Confirm what the selected option includes on the live page.' }]
  },
  't-shirts': { title: 'Oopbuy T-Shirt Spreadsheet', intro: 'A focused starting point for T-shirt finds. Compare the live listing and measurements rather than assuming the title or a saved image tells the whole story.', checklist: ['Check chest width and length against a shirt you already own.', 'Confirm the selected colour and print in the listing photos.', 'Look for current stock and option notes before ordering.'], guideSlug: 'dead-links-and-current-listings', guideLabel: 'What to do when a link changes' },
  jackets: { title: 'Oopbuy Jackets Spreadsheet', intro: 'Browse jacket and outerwear listings with enough context to compare layers, measurements and live availability before deciding what to shortlist.', checklist: ['Check length, shoulder and sleeve measurements for layering room.', 'Review the material and lining notes on the live page.', 'Verify that the chosen colour and size are currently available.'], guideSlug: 'oopbuy-qc-photos', guideLabel: 'Check the QC photo guide' }
};

export const priorityCategorySlugs = ['t-shirts', 'dresses', 'jackets', 'shoes', 'heels', 'trousers-pants', 'eyewear', 'perfume', 'headwear', 'underwear-swim', 'electronics', 'scarves-ties', 'jewelry-watches', 'socks-hosiery'];

Object.assign(focusedCategories, {
  't-shirts': { title: 'Oopbuy T-Shirt Spreadsheet', intro: 'Compare T-shirt listings by fit and current option details before ordering.', checklist: ['Compare chest width and length with a shirt you own.', 'Confirm selected colour and print placement.', 'Check current stock and option notes.'], guideSlug: 'oopbuy-size-guide', guideLabel: 'Read the size guide', research: [{ heading: 'Compare measurements before size labels', paragraphs: ['Use chest width and length from a shirt you already wear as the comparison point. A familiar size label can represent a different cut or measuring method.', 'Confirm the exact selected colour and print on the live listing before keeping an item on your shortlist.'] }], qcChecks: ['Confirm the visible size tag and selected colour.', 'Check print placement, seams and visible label details.', 'QC photos do not guarantee fabric feel or fit.'], faq: [{ question: 'What should I measure for a T-shirt?', answer: 'Compare chest width and length with a T-shirt you already own.' }, { question: 'Can QC photos confirm fit?', answer: 'No. Use actual measurements to assess fit.' }, { question: 'Should I trust the card price?', answer: 'Confirm the exact selected option on the live listing.' }] },
  jackets: { title: 'Oopbuy Jackets Spreadsheet', intro: 'Browse jacket listings with fit, layer room and live specification checks.', checklist: ['Check shoulder, sleeve and length for layering.', 'Confirm lining and material notes.', 'Verify the selected colour and size.'], guideSlug: 'oopbuy-size-guide', guideLabel: 'Read the size guide', research: [{ heading: 'Plan for the way you layer', paragraphs: ['Compare shoulder, chest, sleeve and length measurements with a jacket that fits the way you intend to wear it.', 'Live listing notes about lining, closures and material help distinguish similar-looking outerwear.'] }], qcChecks: ['Confirm size, colour and closure type.', 'Check seams, lining, pockets and visible hardware.', 'QC photos cannot promise warmth or fit.'], faq: [{ question: 'How do I size a jacket?', answer: 'Compare garment measurements with a jacket you already use, allowing for layers.' }, { question: 'What should I check in QC?', answer: 'Confirm the selected size, colour, seams, pockets and closures.' }, { question: 'Can photos prove warmth?', answer: 'No. They only show visible details.' }] },
  jeans: { title: 'Oopbuy Jeans Spreadsheet', intro: 'Compare jeans listings by waist, rise, inseam and current selected option details.', checklist: ['Compare waist, rise and inseam with jeans you own.', 'Confirm wash and selected size.', 'Check the live chart measurement method.'], guideSlug: 'oopbuy-size-guide', guideLabel: 'Read the size guide', research: [{ heading: 'Use garment measurements for denim', paragraphs: ['Compare waist, rise, inseam and leg opening with jeans that fit you. Seller measurements can be flat garment dimensions rather than body dimensions.', 'Confirm the selected wash and size on the live listing because product photos can group several variants.'] }], qcChecks: ['Confirm size tag and wash.', 'Check visible stitching, pockets and hems.', 'QC images do not predict stretch or fit.'], faq: [{ question: 'Which jean measurements matter?', answer: 'Waist, rise, inseam and leg opening are useful comparisons.' }, { question: 'Can I use my usual size?', answer: 'Use the seller chart for the selected option instead.' }, { question: 'What can QC confirm?', answer: 'Visible size, wash and construction details.' }] },
  boots: { title: 'Oopbuy Boots Spreadsheet', intro: 'Compare boot listings by internal length, shaft dimensions and live material details.', checklist: ['Use insole or internal length when available.', 'Check shaft and calf dimensions for taller boots.', 'Confirm sole, colour and selected option.'], guideSlug: 'oopbuy-size-guide', guideLabel: 'Read the size guide', research: [{ heading: 'Compare boot dimensions carefully', paragraphs: ['Internal length is more useful than a familiar size label. For taller styles, compare shaft height and circumference with boots you already wear.', 'Confirm the selected material, sole and colour on the current listing before ordering.'] }], qcChecks: ['Confirm size label and selected colour.', 'Compare left and right boot shape, sole and hardware.', 'QC photos cannot guarantee comfort or weather performance.'], faq: [{ question: 'How do I choose boot size?', answer: 'Use internal length and compare it with boots you own.' }, { question: 'What about tall boots?', answer: 'Check shaft height and circumference as well.' }, { question: 'Do QC photos prove comfort?', answer: 'No. They show visible details only.' }] },
  outerwear: { title: 'Oopbuy Outerwear Spreadsheet', intro: 'Research coats and outerwear through measurements, lining and current option details.', checklist: ['Compare chest, shoulder, length and sleeve measurements.', 'Check lining, closure and material notes.', 'Confirm the exact selected option.'], guideSlug: 'oopbuy-size-guide', guideLabel: 'Read the size guide', research: [{ heading: 'Choose outerwear for the intended layer', paragraphs: ['Outerwear needs room for the layers you plan to wear underneath. Compare garment measurements with an item you already use in similar conditions.', 'Read the current listing for material, lining and closure details instead of relying on a card image.'] }], qcChecks: ['Confirm size, colour and closure.', 'Check visible lining, seams, pockets and hardware.', 'QC photos cannot verify insulation or weather protection.'], faq: [{ question: 'How should outerwear fit?', answer: 'Compare with an outer layer you own and allow room for intended layers.' }, { question: 'What should I check in QC?', answer: 'Visible size, colour, lining, seams and closures.' }, { question: 'Can pictures prove warmth?', answer: 'No. They cannot verify insulation performance.' }] },
  shoes: { title: 'Oopbuy Shoes Spreadsheet', intro: 'Browse shoe listings and verify the exact model, internal length and selected live option.', checklist: ['Use insole or internal length where available.', 'Confirm the model, colour and size.', 'Review the current seller photos and option details.'], guideSlug: 'oopbuy-qc-photos', guideLabel: 'Read the QC guide', research: [{ heading: 'Keep shoe comparison specific', paragraphs: ['Compare internal length with footwear you own rather than assuming standard labels fit the same across listings.', 'Treat the live page as the source for model, colour, material and available size information.'] }], qcChecks: ['Confirm selected size and colour.', 'Compare left and right shoe, sole and visible accessories.', 'QC photos cannot prove comfort, authenticity or durability.'], faq: [{ question: 'How do I choose shoe size?', answer: 'Compare internal length with a pair you already own.' }, { question: 'What does QC confirm?', answer: 'Visible order and construction details.' }, { question: 'Can a card guarantee stock?', answer: 'No. Check the current live listing.' }] }
});
export function categoryContent(slug: string, name: string): CategoryContent {
  return focusedCategories[slug] ?? { title: `${name} Oopbuy Spreadsheet`, intro: `Browse ${name.toLowerCase()} listings with current price context and images, then verify the live listing details before you place an order.`, checklist: ['Review live product photos and option details.', 'Check measurements, price and current availability.', 'Use an official agent site for payment and delivery steps.'], guideSlug: 'how-to-use-oopbuy-spreadsheet', guideLabel: 'Read the spreadsheet guide' };
}
