type CategoryContent = { title: string; intro: string; checklist: string[]; guideSlug: string; guideLabel: string };

const focusedCategories: Record<string, CategoryContent> = {
  sneakers: { title: 'Oopbuy Sneaker Spreadsheet', intro: 'Browse sneaker listings by style and price context, then verify the exact colourway, size chart and live seller photos before adding anything to your agent.', checklist: ['Match the colourway and SKU details to the current listing.', 'Use the seller’s insole or length measurements, not just your usual size.', 'Compare current photos, price and available variants before ordering.'], guideSlug: 'qc-photo-checklist', guideLabel: 'Read the QC photo checklist' },
  'hoodies-sweatshirts': { title: 'Oopbuy Hoodies & Sweatshirts Spreadsheet', intro: 'Use this category to discover hoodies and sweatshirts, compare price ranges and move from a quick shortlist to the live listing with the details that matter.', checklist: ['Check garment measurements for chest, length and shoulder width.', 'Confirm fabric, colour and print details in the current seller photos.', 'Review the live size options before you submit the link.'], guideSlug: 'how-to-use-oopbuy-spreadsheet', guideLabel: 'How to use a spreadsheet well' },
  't-shirts': { title: 'Oopbuy T-Shirt Spreadsheet', intro: 'A focused starting point for T-shirt finds. Compare the live listing and measurements rather than assuming the title or a saved image tells the whole story.', checklist: ['Check chest width and length against a shirt you already own.', 'Confirm the selected colour and print in the listing photos.', 'Look for current stock and option notes before ordering.'], guideSlug: 'dead-links-and-current-listings', guideLabel: 'What to do when a link changes' },
  jackets: { title: 'Oopbuy Jackets Spreadsheet', intro: 'Browse jacket and outerwear listings with enough context to compare layers, measurements and live availability before deciding what to shortlist.', checklist: ['Check length, shoulder and sleeve measurements for layering room.', 'Review the material and lining notes on the live page.', 'Verify that the chosen colour and size are currently available.'], guideSlug: 'qc-photo-checklist', guideLabel: 'Check the QC photo checklist' },
  'bags-backpacks': { title: 'Oopbuy Bags & Backpacks Spreadsheet', intro: 'Explore bags and backpacks by type, then check dimensions, closure details and interior photos on the live listing before you order.', checklist: ['Compare listed dimensions with what you actually need to carry.', 'Check strap, zip and interior details in the current photos.', 'Confirm the live colour and material options before ordering.'], guideSlug: 'how-to-use-oopbuy-spreadsheet', guideLabel: 'Read the spreadsheet guide' },
};

export const priorityCategorySlugs = ['sneakers', 'hoodies-sweatshirts', 't-shirts', 'jackets', 'bags-backpacks'];

export function categoryContent(slug: string, name: string): CategoryContent {
  return focusedCategories[slug] ?? { title: `${name} Oopbuy Spreadsheet`, intro: `Browse ${name.toLowerCase()} listings with current price context and images, then verify the live listing details before you place an order.`, checklist: ['Review live product photos and option details.', 'Check measurements, price and current availability.', 'Use an official agent site for payment and delivery steps.'], guideSlug: 'how-to-use-oopbuy-spreadsheet', guideLabel: 'Read the spreadsheet guide' };
}
