export type CommunityTopic = { slug:string; number:string; label:'Oopbuy haul'|'Community reference'; title:string; sourceUrl:string; subreddit:string; agent:string; weight:string; commentTakeaway:string; postTakeaway:string; related:{label:string;href:string} };
const item=(slug:string,number:string,label:'Oopbuy haul'|'Community reference',title:string,sourceUrl:string,subreddit:string,agent:string,weight:string,commentTakeaway:string,postTakeaway:string,related:{label:string;href:string}):CommunityTopic=>({slug,number,label,title,sourceUrl,subreddit,agent,weight,commentTakeaway,postTakeaway,related});
export const communityTopics:CommunityTopic[]=[
item('oopbuy-33kg-germany','01','Oopbuy haul','Oopbuy 33KG designer-heavy haul to Germany','https://www.reddit.com/r/CnRepsSpreadsheet/comments/1ro1jgw/oopbuy_33kg_designerheavy_haul_to_germany/','r/CnRepsSpreadsheet','Oopbuy','33kg · Germany','Most replies ask for direct item links, especially outerwear, belts and trainers.','A large mixed designer rotation covering sneakers, outerwear, shirts and accessories.',{label:'Browse categories',href:'/categories/'}),
item('oopbuy-18kg-germany','02','Oopbuy haul','18 KG haul to Germany · Part 1','https://www.reddit.com/r/oopbuy/comments/1oryjmt/18_kg_haul_to_part_1/','r/oopbuy','Oopbuy','18kg · Germany','Commenters ask about total cost, item quality and how individual sizes fit.','A linked multi-item haul with footwear, knitwear, accessories and outerwear.',{label:'Read the size guide',href:'/guides/oopbuy-size-guide/'}),
item('oopbuy-good-finds','03','Oopbuy haul','Some good finds · Oopbuy','https://www.reddit.com/r/oopbuy/comments/1i23bss/some_good_finds_ooopbuy/','r/oopbuy','Oopbuy','Finds roundup','Use the original thread for the poster’s exact product context and replies.','A public Oopbuy product-finds discussion.',{label:'Browse current finds',href:'/categories/'}),
item('oopbuy-9kg-germany','04','Oopbuy haul','My best Oopbuy haul so far · 9kg to Germany','https://www.reddit.com/r/oopbuy/comments/1ozh10v/my_best_oopbuy_haul_so_far_9_kg_to/','r/oopbuy','Oopbuy','9kg · Germany','Replies focus on shipping, product links and how specific windbreakers and belts fit.','A multi-category unboxing post with the author’s item-level fit notes.',{label:'Read the shipping guide',href:'/guides/oopbuy-shipping-guide/'}),
item('oopbuy-dior-b30','05','Oopbuy haul','Dior B30 · Oopbuy','https://www.reddit.com/r/oopbuy/comments/1m9p3z8/dior_b30_26/','r/oopbuy','Oopbuy','Single-item review','Read the original comment thread for the poster’s specific questions and follow-ups.','A public Oopbuy sneaker review post.',{label:'QC photo checklist',href:'/guides/oopbuy-qc-photos/'}),
item('oopbuy-13kg-uk','06','Oopbuy haul','13kg Oopbuy haul to UK · shipping review','https://www.reddit.com/r/Yupoo/comments/1w02f4k/13_kg_oopbuy_haul_to_uk_11_day_shipping/','r/Yupoo','Oopbuy','13kg · UK','Treat a single delivery report as an individual experience, not a delivery promise.','A public Oopbuy haul and shipping post.',{label:'Shipping guide',href:'/guides/oopbuy-shipping-guide/'}),
item('room-decor-80kg','07','Community reference','80kg ultra-niche room decor haul','https://www.reddit.com/r/TheRepArchive/comments/1qywahg/80kg_ultra_niche_mainly_room_decor_haul/','r/TheRepArchive','Other agent','80kg · Room decor','Useful as a product-category and haul-documentation reference only.','A non-Oopbuy community haul centred on room decor.',{label:'Explore categories',href:'/categories/'}),
item('hoodie-superbuy','08','Community reference','Hoodies · recent pickups and haul review','https://www.reddit.com/r/FashionReps/comments/1w0p8oq/hoodies_recent_pickups_haul_review_superbuy_dhl/','r/FashionReps','Superbuy','Hoodie review','Fit questions and follow-up photos are recurring discussion needs in haul threads.','A non-Oopbuy clothing review reference.',{label:'Size guide',href:'/guides/oopbuy-size-guide/'}),
item('fashionreps-15kg','09','Community reference','15kg haul review','https://www.reddit.com/r/FashionReps/comments/1vzv7ti/review_15kg_haul/','r/FashionReps','Other agent','15kg · Review','Comments concentrate on sizing, fit, materials and requests for product links.','A detailed non-Oopbuy item-review format reference.',{label:'How to compare listings',href:'/blog/how-to-compare-oopbuy-product-links/'}),
item('stockholm-haul','10','Community reference','Haul to Stockholm','https://www.reddit.com/r/stockholmreps/comments/1vytu8x/haul_to/','r/stockholmreps','Other agent','Stockholm','Open the original thread for its specific route and item context.','A non-Oopbuy regional haul reference.',{label:'Buyer guides',href:'/guides/'})
];
export const getCommunityTopic=(slug:string)=>communityTopics.find(topic=>topic.slug===slug);
