export const countryAlternates = [
  { hreflang: 'x-default', href: 'https://oopbuytop.net/' },
  { hreflang: 'en', href: 'https://oopbuytop.net/' },
  { hreflang: 'de-DE', href: 'https://oopbuytop.net/de/oopbuy-spreadsheet/' },
  { hreflang: 'en-GB', href: 'https://oopbuytop.net/uk/oopbuy-spreadsheet/' },
  { hreflang: 'en-US', href: 'https://oopbuytop.net/us/oopbuy-spreadsheet/' },
  { hreflang: 'en-CA', href: 'https://oopbuytop.net/ca/oopbuy-spreadsheet/' },
  { hreflang: 'en-AU', href: 'https://oopbuytop.net/au/oopbuy-spreadsheet/' },
  { hreflang: 'fr-FR', href: 'https://oopbuytop.net/fr/oopbuy-spreadsheet/' },
];

export const countryLandingConfigs = [
  {
    slug: 'us',
    lang: 'en-US',
    locale: 'en-US',
    country: 'United States',
    shortCountry: 'USA',
    currency: 'USD',
    symbol: '$',
    title: 'Oopbuy Spreadsheet USA 2026: Finds, Prices & QC',
    descriptionLead: 'US-focused Oopbuy spreadsheet',
    heroLead: 'finds with USD, sizing and QC context',
    intro: 'Research the current catalogue by product or category. Start with focused finds that report warehouse-photo references, then check the selected option and delivered-cost details for your US address.',
    checklistTitle: 'US research checklist',
    checklist: [
      'Treat the listed item price and delivered total as separate numbers.',
      'Compare measurements instead of relying on US size labels alone.',
      'Confirm the current carrier, restrictions and charges for your state.',
    ],
    steps: [
      { title: 'Build a short, comparable list', text: 'Search one model or product type at a time. Open a few relevant research pages and compare the same evidence on each: live variant, measurements, current images and QC-photo availability.' },
      { title: 'Convert measurements carefully', text: 'For clothing, compare chest, length, shoulder and sleeve measurements with something you own. For footwear, use internal or insole length where available instead of trusting a US conversion in isolation.' },
      { title: 'Estimate the delivered USD total', text: 'A product snapshot is not a delivered quote. Variant price, exchange rate, domestic handling, international shipping, optional services and destination charges can change the final total.' },
    ],
    categorySlugs: ['sneakers', 'hoodies-sweatshirts', 't-shirts', 'jackets', 'electronics', 'jewelry-watches'],
    categoryLabels: ['Sneakers', 'Hoodies', 'T-shirts', 'Jackets', 'Electronics', 'Jewelry'],
    focusCategories: ['sneakers', 'hoodies-sweatshirts', 't-shirts', 'jackets', 'electronics', 'jewelry-watches'],
    faqHeading: 'Oopbuy spreadsheet USA questions',
    faq: [
      { question: 'Is this Oopbuy spreadsheet specifically for US shoppers?', answer: 'It combines the main research catalogue with US-focused currency, measurement and parcel checks. Current checkout and carrier details still need to be verified for the exact destination.' },
      { question: 'Are card prices final delivered USD prices?', answer: 'No. They are catalogue snapshots. The selected variant, shipping, services, exchange rate and possible destination charges are separate.' },
      { question: 'Can I rely on a US size conversion?', answer: 'Use it only as a starting point. Compare the current seller measurements with an item or shoe that already fits.' },
      { question: 'Do QC photos prove product quality?', answer: 'No. They can reveal visible mismatches or defects, but they do not guarantee quality, authenticity, fit, function or durability.' },
    ],
  },
  {
    slug: 'ca',
    lang: 'en-CA',
    locale: 'en-CA',
    country: 'Canada',
    shortCountry: 'Canada',
    currency: 'CAD',
    symbol: 'C$',
    title: 'Oopbuy Spreadsheet Canada 2026: Finds, Prices & QC',
    descriptionLead: 'Canadian Oopbuy spreadsheet',
    heroLead: 'finds with CAD and parcel-planning context',
    intro: 'Search the catalogue by category, model or product name. Use QC-reference finds to form a shortlist, then recalculate currency, parcel weight and destination charges for your Canadian address.',
    checklistTitle: 'Canada research checklist',
    checklist: [
      'Convert the live option price to CAD, not just the card snapshot.',
      'Check garment and footwear measurements before choosing a size.',
      'Verify current carrier and import information for your province.',
    ],
    steps: [
      { title: 'Compare like with like', text: 'Keep each shortlist within one product family so price, measurements and QC-photo coverage stay comparable. A smaller set of well-documented finds is easier to review than a large mixed list.' },
      { title: 'Record the exact option and size', text: 'Save the colour, size and selected variant before the warehouse stage. Compare centimetre measurements with an item you own; generic Canadian or US labels alone are not enough.' },
      { title: 'Plan the CAD parcel total', text: 'Separate product cost from international delivery. Weight, package volume, services, exchange rates and current destination charges can all change the amount paid.' },
    ],
    categorySlugs: ['shoes', 'hoodies-sweatshirts', 'jackets', 'boots', 'bags-backpacks', 'electronics'],
    categoryLabels: ['Shoes', 'Hoodies', 'Jackets', 'Boots', 'Bags', 'Electronics'],
    focusCategories: ['shoes', 'hoodies-sweatshirts', 'jackets', 'boots', 'bags-backpacks', 'electronics'],
    faqHeading: 'Oopbuy spreadsheet Canada questions',
    faq: [
      { question: 'Is this Oopbuy spreadsheet useful for Canadian buyers?', answer: 'Yes as a research index. It adds Canadian currency and parcel-planning context, while current carrier, availability and destination information must still be checked live.' },
      { question: 'Are the displayed prices in Canadian dollars?', answer: 'Not necessarily. Product cards are catalogue snapshots, so convert the selected live variant and keep shipping and destination costs separate.' },
      { question: 'How should I compare sizes in Canada?', answer: 'Use centimetre measurements from the current listing and compare them with an item that fits. Do not rely on a familiar size label alone.' },
      { question: 'Does a QC-photo count mean an item is recommended?', answer: 'No. It only reports photo references in the catalogue snapshot and is not a quality score or endorsement.' },
    ],
  },
  {
    slug: 'au',
    lang: 'en-AU',
    locale: 'en-AU',
    country: 'Australia',
    shortCountry: 'Australia',
    currency: 'AUD',
    symbol: 'A$',
    title: 'Oopbuy Spreadsheet Australia 2026: Finds & QC',
    descriptionLead: 'Australian Oopbuy spreadsheet',
    heroLead: 'finds with AUD and long-distance parcel checks',
    intro: 'Browse current catalogue records and focused QC-reference finds before checking the live option. Australian shoppers should compare measurements and model a delivered AUD total rather than judging an item from its snapshot price.',
    checklistTitle: 'Australia research checklist',
    checklist: [
      'Recalculate the selected option and parcel cost in AUD.',
      'Use centimetre measurements for apparel and internal shoe length.',
      'Review current route availability and destination rules before payment.',
    ],
    steps: [
      { title: 'Start with evidence-rich finds', text: 'Search a narrow category or model and prioritise pages with useful images, clear option names and measurement context. Skip listings that cannot answer your first fit or product question.' },
      { title: 'Use centimetres as the common language', text: 'Compare seller measurements with an item you already own. This is more reliable than moving directly between AU, EU, UK or generic international labels.' },
      { title: 'Model the delivered AUD cost', text: 'Long-distance shipping can materially change the decision. Recheck chargeable weight, packaging, services, exchange rate and current destination information before placing an order.' },
    ],
    categorySlugs: ['t-shirts', 'sandals-slippers', 'sneakers', 'shorts', 'eyewear', 'accessory-others'],
    categoryLabels: ['T-shirts', 'Sandals', 'Sneakers', 'Shorts', 'Eyewear', 'Accessories'],
    focusCategories: ['t-shirts', 'sandals-slippers', 'sneakers', 'shorts', 'eyewear', 'accessory-others'],
    faqHeading: 'Oopbuy spreadsheet Australia questions',
    faq: [
      { question: 'Is this an Australian Oopbuy spreadsheet?', answer: 'It is an independent catalogue view with Australian currency, sizing and parcel-planning context. Live seller and carrier information always takes precedence.' },
      { question: 'Does the listed price include delivery to Australia?', answer: 'No. Card prices are product snapshots. International shipping, services, exchange rates and possible destination charges are separate.' },
      { question: 'Should I order my normal Australian size?', answer: 'Not without checking. Compare centimetre measurements and the seller measuring method with an item that already fits.' },
      { question: 'Are all finds checked by OopbuyTop?', answer: 'The catalogue records available product data and QC-photo references, but does not independently authenticate, grade or guarantee listed products.' },
    ],
  },
  {
    slug: 'fr',
    lang: 'fr-FR',
    locale: 'fr-FR',
    country: 'France',
    shortCountry: 'France',
    currency: 'EUR',
    symbol: '€',
    title: 'Oopbuy Spreadsheet France 2026 : trouvailles et QC',
    descriptionLead: 'Oopbuy Spreadsheet France',
    heroLead: 'des trouvailles avec prix et contexte QC',
    intro: 'Parcourez le catalogue par produit ou catégorie. Commencez par les fiches qui signalent des références de photos QC, puis vérifiez la variante, les mesures et le coût livré pour votre adresse en France.',
    checklistTitle: 'Checklist pour la France',
    checklist: [
      'Ne pas confondre le prix de l’article avec le total livré en euros.',
      'Comparer les mesures réelles plutôt que la seule étiquette de taille.',
      'Vérifier les transporteurs et informations d’importation actuels.',
    ],
    steps: [
      { title: 'Créer une sélection courte', text: 'Recherchez un type de produit, une marque ou un modèle précis, puis comparez quelques fiches pertinentes. Vérifiez la variante en direct, les images, les mesures et la disponibilité des références QC.' },
      { title: 'Comparer les mesures en centimètres', text: 'Pour les vêtements, comparez largeur, longueur, épaules et manches avec une pièce qui vous va. Pour les chaussures, privilégiez la longueur intérieure lorsqu’elle est disponible.' },
      { title: 'Séparer le prix et le colis', text: 'Le prix affiché n’est pas un devis livré en euros. La variante, le taux de change, le transport, les services et les éventuels frais à destination peuvent modifier le total.' },
    ],
    categorySlugs: ['perfume', 'sneakers', 'bags-backpacks', 'jackets', 'jewelry-watches', 'scarves-ties'],
    categoryLabels: ['Parfums', 'Sneakers', 'Sacs', 'Vestes', 'Bijoux', 'Foulards'],
    focusCategories: ['perfume', 'sneakers', 'bags-backpacks', 'jackets', 'jewelry-watches', 'scarves-ties'],
    faqHeading: 'Questions sur Oopbuy Spreadsheet France',
    faq: [
      { question: 'Cette Oopbuy Spreadsheet est-elle adaptée à la France ?', answer: 'Cette page ajoute un contexte français pour la devise, les tailles et la préparation du colis. Les informations en direct du vendeur et du transporteur restent prioritaires.' },
      { question: 'Les prix affichés sont-ils des prix livrés en euros ?', answer: 'Non. Ce sont des instantanés du catalogue. La variante, la conversion, le transport, les services et les éventuels frais à destination sont distincts.' },
      { question: 'Comment choisir une taille française ?', answer: 'Comparez les mesures actuelles en centimètres avec un vêtement ou une chaussure qui vous va. Une conversion générique ne suffit pas.' },
      { question: 'Les photos QC garantissent-elles la qualité ?', answer: 'Non. Elles peuvent aider à repérer un défaut visible ou une mauvaise variante, mais ne garantissent ni la qualité, ni l’authenticité, ni la durabilité.' },
    ],
  },
] as const;
