type Guide = { title: string; group: string; description: string; intro: string; steps: string[]; sections: { heading: string; paragraphs: string[] }[] };
const makeGuide = (title: string, group: string, description: string, intro: string, first: string, second: string): Guide => ({ title, group, description, intro, sections: [{ heading: 'What to focus on', paragraphs: [first, 'Use the guide as a way to structure research, then compare the live listing before you make a decision. Listings, variants and availability can change.'] }, { heading: 'Keep the next step current', paragraphs: [second, 'Use the official service you choose for account, payment, shipping and support actions.'] }], steps: ['Start with one focused category or listing.', 'Compare the visible details that affect your choice.', 'Confirm the current live information.', 'Decide before moving to shipping.'] });

export const guides: Record<string, Guide> = {
  'how-to-use-oopbuy-spreadsheet': makeGuide('How to Use an Oopbuy Spreadsheet', 'Getting started', 'A category-to-listing workflow for your first research session.', 'A spreadsheet is useful for discovery, not a substitute for reviewing the current listing.', 'Start with a category rather than one long list. Compare title, price context, images and QC availability before shortlisting an item.', 'The live listing is the final source for selectable options, measurements and availability.'),
  'oopbuy-beginner-checklist': makeGuide('Oopbuy Beginner Checklist', 'Getting started', 'A calm first-order research checklist.', 'A short checklist prevents rushed decisions when you are using a product-discovery guide for the first time.', 'Build a small shortlist and compare similar items instead of saving every link you see.', 'Move from category, to live listing, to QC review, to shipping so each decision stays clear.'),
  'dead-links-and-current-listings': makeGuide('What to Do When a Product Link Is Dead', 'Getting started', 'How to return to a current listing instead of trusting old product data.', 'Marketplace listings change often. A dead link is a prompt to research again, not to rely on an old price or image.', 'A similar title or picture does not guarantee the same seller, variant or product. Treat a replacement as a new item to evaluate.', 'Search the current category, compare live details again, and do not assume an old price still applies.'),
  'oopbuy-price-research': makeGuide('How to Compare Oopbuy Spreadsheet Prices', 'Getting started', 'Compare current price context without treating an old card as a quote.', 'A displayed price is useful context, but the current listing price and options are what matter at checkout.', 'Compare the exact option, quantity and listing version. A low figure may refer to a different variant.', 'Separate the product comparison from parcel and shipping decisions.'),
  'qc-photo-checklist': makeGuide('QC Photo Checklist Before Ordering', 'QC & checks', 'A short checklist for labels, colour, construction and completeness.', 'QC photos can help you spot obvious issues, but they are not a guarantee of fit or final condition.', 'Keep the original listing open and compare the colour, visible label, selected option and important details.', 'Review available photos before an item is included in an international parcel.'),
  'oopbuy-size-guide': makeGuide('How to Read Product Sizes Before Ordering', 'QC & checks', 'Use measurements and labels rather than relying on a size name alone.', 'Size names vary by seller and product type, so the current listing measurements matter most.', 'Compare the current chart with an item you already own and understand how the seller measured it.', 'A visible warehouse label can confirm an option, but it cannot promise fit.'),
  'oopbuy-product-comparison': makeGuide('How to Compare Product Listings', 'QC & checks', 'A repeatable way to compare images, variants and QC availability.', 'Comparing a few relevant listings carefully is more useful than collecting many unreviewed links.', 'Compare title, variant, price context, image coverage and QC availability side by side.', 'When details conflict, prefer the current live listing over an older card.'),
  'oopbuy-spreadsheet-safety': makeGuide('Oopbuy Spreadsheet Safety Checklist', 'QC & checks', 'Keep product research separate from account and payment actions.', 'A discovery guide can organize categories, but it should never replace official account, order or support pages.', 'Treat the guide as a research tool, not a promise about a seller, price, delivery time or outcome.', 'Verify current information on the appropriate official page before you act.'),
  'oopbuy-warehouse-checks': makeGuide('Warehouse Checks Before Shipping', 'Shipping', 'Prepare a parcel only after each item has been deliberately reviewed.', 'Warehouse review is the bridge between product research and parcel planning.', 'Review each item separately so a large parcel does not hide an unresolved question about one item.', 'After item review, check the shipping option currently shown for your destination.'),
};
